#!/bin/bash

echo "🔍 Checking Jaeger for traces..."
echo ""
echo "Jaeger UI: http://localhost:16686"
echo ""
echo "What you should see in Jaeger:"
echo "  1. Service: jobqueue-api"
echo "  2. Operations: POST /auth/token, POST /v1/jobs, GET /health"
echo "  3. Click any trace to see:"
echo "     - HTTP request details"
echo "     - Database queries"
echo "     - Response time"
echo "     - Full timeline"
echo ""
echo "To generate more traces:"
echo "  ./create-demo-jobs.sh demo-tenant 10"
echo ""
echo "Note: Trace IDs will appear in logs after rebuilding images with:"
echo "  ./deploy-local-k8s.sh"
